# services for cube_custom_fields_bundle
#
# no autoconiguration and autowiring, as suggested by best practice in https://symfony.com/doc/current/bundles/best_practices.html#services
# with aliases from the class name to allow usage in autowire

services:
    cube_custom_fields.form_fields:
        class: CubeTools\CubeCustomFieldsBundle\Form\CustomFieldsFormService
        arguments:
            - '%cubetools.customfields.entities%'
            - '@doctrine.orm.entity_manager'
    CubeTools\CubeCustomFieldsBundle\Form\CustomFieldsFormService: '@cube_custom_fields.form_fields'

    CubeTools\CubeCustomFieldsBundle\Entity\EntityCustomField:
        autowire: true
        autoconfigure: true
    CubeTools\CubeCustomFieldsBundle\Utils\:
        autowire: true
        autoconfigure: true
        resource: '../../Utils/*'
        arguments:
            $config: '%cubetools.customfields.entities%'
