#parameters:

services:
    # cube_customfields.service1:
    #     class: CubeTools\CubeCustomFieldsBundle\ClassName
    #     arguments:
    #         - '%kernel.root_dir%'
    # CubeTools\CubeCustomFieldsBundle\ClassName: '@cube_customfields.service1'
